In [2]:
import numpy as np

In [7]:
arr = np.ones((3,4), int)

In [8]:
arr

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [9]:
arr + 5

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

In [10]:
arr * 5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

#### np.empty()

In [16]:
np.empty((2,3), dtype = int)

array([[816034288,       417,         0],
       [        0,    131075, 760946720]])

In [15]:
np.empty((2,3), dtype = str)

array([['', '', ''],
       ['', '', '']], dtype='<U1')

In [17]:
np.empty((3,3), dtype = str)

array([['', '', ''],
       ['', '', ''],
       ['', '', '']], dtype='<U1')

#### np.eye()

In [21]:
np.eye(4, dtype = int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [ ]:
# Optional Things

In [22]:
import pandas as pd

DataFrame: Multiple Rows and Multiple Columns

In [23]:
arr

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [24]:
pd.DataFrame(arr)

0  1  2  3
0  1  1  1  1
1  1  1  1  1
2  1  1  1  1

Explicit indexing is done by pandas

In [25]:
# Extra Topics

In [26]:
import random

Generating Random Data

In [30]:
random.choice((1,2,3,4,5,6))

6

In [35]:
random.choice("Saarthak")

'k'

In [36]:
random.randrange(1,1000)

471

In [38]:
random.random()  # Any random number between 0(included) and 1(excluded).

0.8917077143199416

In [39]:
l = [1,2,3,4,5,6]
random.shuffle(l)

In [40]:
l

[2, 1, 3, 4, 6, 5]

In [44]:
random.uniform(7,14) # A number between 7 and 14 with differnt distribution

8.520335894640068

#### Random np

In [46]:
np.random.rand(3,4)

array([[0.64563111, 0.59036189, 0.5378993 , 0.10963523],
       [0.71861184, 0.17713767, 0.0056014 , 0.4161921 ],
       [0.20026372, 0.17982992, 0.51591419, 0.38541394]])

In [49]:
np.random.rand(1)

array([0.00287692])

In [50]:
np.random.randn(2,3)

array([[ 1.11734466,  1.3436616 , -0.58917437],
       [-2.05264182, -0.64235881,  0.74509125]])

randn --> rand with Normal Distribution

In [51]:
np.random.random_sample()

0.6086861138156152

return random floats in the half-open interval [0.0, 1.0)
  (0 is included and 1 is excluded)

In [52]:
np.random.randint(1,5, size = (3,4))

array([[2, 3, 1, 4],
       [1, 1, 4, 4],
       [1, 2, 2, 2]])

randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).

In [53]:
arr = np.random.randint(1,5, size = (3,4))

In [54]:
arr

array([[1, 4, 2, 1],
       [3, 1, 2, 1],
       [1, 2, 2, 1]])

In [55]:
arr.size

12

In [56]:
arr.shape

(3, 4)

In [57]:
arr.ndim

2

#### Reshape Array

In [58]:
arr.reshape(2,6)

array([[1, 4, 2, 1, 3, 1],
       [2, 1, 1, 2, 2, 1]])

a.reshape(shape, order='C')

Returns an array containing the same data with a new shape.

array size cannot change

reshape(x,y) --> x*y = size of array

In [59]:
arr.reshape(12,2)

ValueError: cannot reshape array of size 12 into shape (12,2)

In [60]:
arr.reshape(12,1)

array([[1],
       [4],
       [2],
       [1],
       [3],
       [1],
       [2],
       [1],
       [1],
       [2],
       [2],
       [1]])

In [62]:
arr.reshape(4, -1)

array([[1, 4, 2],
       [1, 3, 1],
       [2, 1, 1],
       [2, 2, 1]])

-1 when we don't know how many columns we want

In [63]:
arr.reshape(3, -1)

array([[1, 4, 2, 1],
       [3, 1, 2, 1],
       [1, 2, 2, 1]])

In [64]:
arr.reshape(-1, 3)

array([[1, 4, 2],
       [1, 3, 1],
       [2, 1, 1],
       [2, 2, 1]])

In [65]:
arr.reshape(-1, 4)

array([[1, 4, 2, 1],
       [3, 1, 2, 1],
       [1, 2, 2, 1]])

In [66]:
arr.reshape(-1,5)

ValueError: cannot reshape array of size 12 into shape (5)

#### reshape().base  -->  Points out to original array

In [67]:
arr

array([[1, 4, 2, 1],
       [3, 1, 2, 1],
       [1, 2, 2, 1]])

In [70]:
arr.reshape(6,2)

array([[1, 4],
       [2, 1],
       [3, 1],
       [2, 1],
       [1, 2],
       [2, 1]])

In [71]:
arr.reshape(6,2).base

array([[1, 4, 2, 1],
       [3, 1, 2, 1],
       [1, 2, 2, 1]])

.base shows the array to which reshaping was done.

#### Reshape into another dimension

In [72]:
arr

array([[1, 4, 2, 1],
       [3, 1, 2, 1],
       [1, 2, 2, 1]])

In [73]:
arr.size

12

In [74]:
arr.ndim

2

In [78]:
arr2 = arr.reshape(2,3,2)

In [79]:
arr2

array([[[1, 4],
        [2, 1],
        [3, 1]],

       [[2, 1],
        [1, 2],
        [2, 1]]])

In [80]:
arr2.ndim

3

In [81]:
arr3 = arr.reshape(1,2,3,2)

In [82]:
arr3

array([[[[1, 4],
         [2, 1],
         [3, 1]],

        [[2, 1],
         [1, 2],
         [2, 1]]]])

In [83]:
arr3.ndim

4

#### Dimension Concepts

In [84]:
l = [1,2,3,4]

In [86]:
arr = np.array(l)

In [87]:
arr

array([1, 2, 3, 4])

In [88]:
arr.ndim

1

In [90]:
arr2 = np.array([[2,3],[4,5]])

In [91]:
arr2

array([[2, 3],
       [4, 5]])

In [92]:
arr2.ndim

2

In [93]:
arr2 = np.zeros((3,4))

In [94]:
arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [95]:
arr2.ndim

2

In [96]:
arr3 = np.zeros((1,3,4))  # 3 Rows & 4 Columns with 1 Extra Dimensions

In [97]:
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [98]:
arr3.ndim

3

In [99]:
arr3.shape

(1, 3, 4)

In [100]:
arr4 = np.zeros((1,2,2,3))

In [101]:
arr4

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [102]:
arr4.ndim

4

In [103]:
arr4.shape

(1, 2, 2, 3)

In [104]:
arr5 = np.zeros((2,3,4)) # 3by4 Matrix repeated twice in the extra dimension

In [105]:
arr5

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [106]:
arr5.ndim

3

In [107]:
arr5.shape

(2, 3, 4)

#### Operations on np-array

In [110]:
arr1 = np.random.randint(1,10,(5,6))

In [111]:
arr1

array([[5, 7, 4, 6, 8, 7],
       [6, 6, 2, 2, 6, 8],
       [7, 3, 3, 7, 4, 7],
       [1, 9, 1, 6, 2, 2],
       [3, 2, 6, 3, 3, 3]])

In [114]:
arr1>5

array([[False,  True, False,  True,  True,  True],
       [ True,  True, False, False,  True,  True],
       [ True, False, False,  True, False,  True],
       [False,  True, False,  True, False, False],
       [False, False,  True, False, False, False]])

In [113]:
arr1[arr1>5]

array([7, 6, 8, 7, 6, 6, 6, 8, 7, 7, 7, 9, 6, 6])

All the elements of arr1 where arr1>5 this condition is true

In [118]:
arr1[arr1 == 5]

array([5])

#### Accessing elements and matrixs from array

In [119]:
arr

array([1, 2, 3, 4])

In [120]:
arr[0]

1

In [121]:
arr1

array([[5, 7, 4, 6, 8, 7],
       [6, 6, 2, 2, 6, 8],
       [7, 3, 3, 7, 4, 7],
       [1, 9, 1, 6, 2, 2],
       [3, 2, 6, 3, 3, 3]])

In [123]:
arr1[0,0]

5

In [124]:
arr1[0,1:4]

array([7, 4, 6])

In [127]:
arr1[0,[1,4]]

array([7, 8])

In [125]:
arr1[1:4, 2:5]

array([[2, 2, 6],
       [3, 7, 4],
       [1, 6, 2]])

In [135]:
arr1[[2,4],[2,4]]

array([3, 3])

In [133]:
arr1[2:,2:4]

array([[3, 7],
       [1, 6],
       [6, 3]])

In [136]:
arr1[[0,4], ]

array([[5, 7, 4, 6, 8, 7],
       [3, 2, 6, 3, 3, 3]])

In [140]:
arr1[[0,4], 0:3]

array([[5, 7, 4],
       [3, 2, 6]])

#### Operations on 2 arrays

In [141]:
arr1 = np.random.randint(1,3,(3,3))

In [142]:
arr1

array([[2, 2, 2],
       [1, 2, 1],
       [2, 1, 1]])

In [143]:
arr2 = np.random.randint(1,3,(3,3))

In [144]:
arr2

array([[2, 2, 2],
       [2, 1, 1],
       [2, 2, 1]])

In [145]:
arr1 + arr2

array([[4, 4, 4],
       [3, 3, 2],
       [4, 3, 2]])

In [146]:
arr1 * arr2

array([[4, 4, 4],
       [2, 2, 1],
       [4, 2, 1]])

In [147]:
arr1 - arr2

array([[ 0,  0,  0],
       [-1,  1,  0],
       [ 0, -1,  0]])

In [148]:
arr1 // arr2

array([[1, 1, 1],
       [0, 2, 1],
       [1, 0, 1]])

In [149]:
arr1 % arr2

array([[0, 0, 0],
       [1, 0, 0],
       [0, 1, 0]])