# Numerical Python - NumPy

In [1]:
import numpy as np  # 2005 by Travis Oliphant, documented in C++ for faster execution of mathematical formulas

In [2]:
np.__version__

'1.24.3'

In [3]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

### Why NumPy

- Mathematical functions
- Faster execution

In [4]:
l = [1,2,3,4,5]

In [8]:
arr = np.array(l)
arr

array([1, 2, 3, 4, 5])

In [9]:
type(np.array(l))

numpy.ndarray

##### numpy.ndarray - n dimensional array

- array is the way numpy stores the data.
- stores only same (homogeneous) type of data. 

In [10]:
arr.ndim

1

In [11]:
l1 = [1,2,3,4,5,"rishi"]

In [13]:
arr1 = np.array(l1)
arr1

array(['1', '2', '3', '4', '5', 'rishi'], dtype='<U11')

np.array converts all elements in homogenous data type

In [14]:
arr1.ndim

1

In [15]:
arr2 = np.array([[1,2,3],[4,5,6]])

In [16]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
arr2.ndim

2

In [23]:
arr3 = np.array([[[2,3,4],[5,6,7],[8,9,0]]])

In [24]:
arr3

array([[[2, 3, 4],
        [5, 6, 7],
        [8, 9, 0]]])

In [25]:
arr3.ndim

3

In [26]:
l = [1,2,3,4]

In [28]:
a = np.array(l)

In [33]:
a

array([1, 2, 3, 4])

In [34]:
a.ndim

1

In [35]:
b = np.matrix(l)

In [36]:
b

matrix([[1, 2, 3, 4]])

In [37]:
b.ndim

2

Matrix is by default 2-dimensional

In [40]:
np.matrix([[[2,3,4],[5,6,7],[8,9,0]]])

ValueError: matrix must be 2-dimensional

More way to convert to array

- np.asarray()
- np.asanyarray()      # Convert the input to an ndarray, but pass ndarray subclasses through.

In [41]:
np.asarray([[[2,3,4],[5,6,7],[8,9,0]]])

array([[[2, 3, 4],
        [5, 6, 7],
        [8, 9, 0]]])

In [44]:
np.asanyarray([[[2,3,4],[5,6,7],[8,9,0]]])

array([[[2, 3, 4],
        [5, 6, 7],
        [8, 9, 0]]])

In [48]:
mat = np.matrix([1,2,3,4])

In [49]:
mat

matrix([[1, 2, 3, 4]])

In [50]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4]])

In [51]:
t = ([1,2,3],[4,5,6])
type(t)

tuple

In [52]:
np.array(t)

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
s = 5
np.array(s)

array(5)

###### Deep Copy and Shallow Copy

In [72]:
l = [1,2,3,4,5]
arr = np.array(l)
arr

array([1, 2, 3, 4, 5])

In [73]:
a = arr

In [74]:
b = arr.copy()

In [75]:
a

array([1, 2, 3, 4, 5])

In [76]:
b

array([1, 2, 3, 4, 5])

In [77]:
arr[0] = 100

In [78]:
arr

array([100,   2,   3,   4,   5])

In [79]:
a  # Shallow Copy

array([100,   2,   3,   4,   5])

In [80]:
b  # Deep Copy

array([1, 2, 3, 4, 5])

In [81]:
b[0] = 200
b

array([200,   2,   3,   4,   5])

In [82]:
arr

array([100,   2,   3,   4,   5])

### Generating Array

- np.fromfunction()
- np.fromiter()
- np.fromstring()
- np.arange(start, end, step)
- np.linspace(start, end, no. of elements)
- np.logspace(start, end, no. of elements, base = x)
- np.zeros()
- np.ones()

In [85]:
np.fromfunction(lambda i,j : i==j, shape = (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [86]:
arr1

array(['1', '2', '3', '4', '5', 'rishi'], dtype='<U11')

In [87]:
arr1.shape

(6,)

In [89]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [90]:
arr2.shape

(2, 3)

In [91]:
arr1.size

6

In [92]:
arr2.size

6

###### Functions

In [93]:
np.fromfunction(lambda i,j : i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [94]:
for i in range(5):
    print(i)

0
1
2
3
4


In [95]:
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [96]:
list(i for i in range(5))

[0, 1, 2, 3, 4]

In [97]:
list(range(5))

[0, 1, 2, 3, 4]


###### Iterables

In [108]:
iterable = (i*i for i in range(5))

In [106]:
np.fromiter(iterable, int)

array([ 0,  1,  4,  9, 16])

In [109]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

###### String

In [101]:
np.fromstring('23 45 67', sep=" ")

array([23., 45., 67.])

In [102]:
np.fromstring('23,45,67', sep=",")

array([23., 45., 67.])

In [103]:
np.fromstring('Saar,Buggu', sep=",")

C:\Users\saart\AppData\Local\Temp\ipykernel_15792\1807035823.py:1: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  np.fromstring('Saar,Buggu', sep=",")


array([], dtype=float64)

In [110]:
arr1

array(['1', '2', '3', '4', '5', 'rishi'], dtype='<U11')

In [111]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [112]:
arr2.dtype

dtype('int32')

In [113]:
arr

array([100,   2,   3,   4,   5])

In [114]:
arr.dtype

dtype('int32')

In [115]:
list(range(5))

[0, 1, 2, 3, 4]

In [116]:
range(5)

range(0, 5)

In [117]:
list(range(1.0,2.10))

TypeError: 'float' object cannot be interpreted as an integer

###### a-range

In [122]:
np.arange(0.1,11,0.2)

array([ 0.1,  0.3,  0.5,  0.7,  0.9,  1.1,  1.3,  1.5,  1.7,  1.9,  2.1,
        2.3,  2.5,  2.7,  2.9,  3.1,  3.3,  3.5,  3.7,  3.9,  4.1,  4.3,
        4.5,  4.7,  4.9,  5.1,  5.3,  5.5,  5.7,  5.9,  6.1,  6.3,  6.5,
        6.7,  6.9,  7.1,  7.3,  7.5,  7.7,  7.9,  8.1,  8.3,  8.5,  8.7,
        8.9,  9.1,  9.3,  9.5,  9.7,  9.9, 10.1, 10.3, 10.5, 10.7, 10.9])

In [124]:
list(np.arange(0.1,11,0.2))

[0.1,
 0.30000000000000004,
 0.5000000000000001,
 0.7000000000000001,
 0.9000000000000001,
 1.1000000000000003,
 1.3000000000000003,
 1.5000000000000004,
 1.7000000000000004,
 1.9000000000000004,
 2.1000000000000005,
 2.3000000000000007,
 2.5000000000000004,
 2.7000000000000006,
 2.900000000000001,
 3.1000000000000005,
 3.3000000000000007,
 3.500000000000001,
 3.7000000000000006,
 3.900000000000001,
 4.1000000000000005,
 4.300000000000001,
 4.500000000000001,
 4.7,
 4.9,
 5.1000000000000005,
 5.300000000000001,
 5.500000000000001,
 5.700000000000001,
 5.9,
 6.1000000000000005,
 6.300000000000001,
 6.500000000000001,
 6.700000000000001,
 6.900000000000001,
 7.100000000000001,
 7.300000000000001,
 7.500000000000001,
 7.700000000000001,
 7.900000000000001,
 8.100000000000001,
 8.3,
 8.500000000000002,
 8.700000000000001,
 8.900000000000002,
 9.100000000000001,
 9.3,
 9.500000000000002,
 9.700000000000001,
 9.900000000000002,
 10.100000000000001,
 10.300000000000002,
 10.500000000000002,
 

###### linspace (starting value ,end value, Number of elements)

In [125]:
np.linspace(1,5,20) # linspace(starting value ,end value, Number of elements)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

###### logspace(starting value ,end value, Number of elements, base = x)

In [126]:
np.logspace(1, 5, 10, base = 2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [127]:
np.logspace(1, 5, 10, base = 10)

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

###### Zeros (dim, row, col)

In [133]:
z1 = np.zeros(5, int)

In [134]:
z1

array([0, 0, 0, 0, 0])

In [135]:
z2 = np.zeros((3,4))

In [136]:
z2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [138]:
z1.shape

(5,)

In [139]:
z2.shape

(3, 4)

In [142]:
z3 = np.zeros((3,3,4), int)  # Repeat (3,4) matrix 3 times

In [143]:
z3

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [144]:
z3.shape

(3, 3, 4)

In [145]:
z3.ndim

3

In [149]:
z4 = np.zeros((1,3,3,4), int)

In [150]:
z4

array([[[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]]])

In [152]:
z4.shape

(1, 3, 3, 4)

In [153]:
z4.ndim

4

###### Ones(dim, row, col)

In [154]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [157]:
o = np.ones((3,4), int)

In [158]:
o

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [160]:
o + 2

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [162]:
o * 5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])