In [1]:
import numpy as np

In [2]:
data = np.array([[1],[2],[3]])

In [3]:
data

array([[1],
       [2],
       [3]])

In [4]:
data.ndim

2

In [5]:
a = np.squeeze(data)

In [6]:
a

array([1, 2, 3])

In [7]:
np.squeeze(a)

array([1, 2, 3])

In [8]:
a.ndim

1

##### Repeat

In [9]:
data

array([[1],
       [2],
       [3]])

In [10]:
np.repeat(data,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [11]:
b = np.array([[1,2],[3,4]])

In [12]:
b

array([[1, 2],
       [3, 4]])

In [13]:
b1 = np.repeat(b,2)

In [14]:
b1

array([1, 1, 2, 2, 3, 3, 4, 4])

In [15]:
np.repeat(b,2, axis=1)

array([[1, 1, 2, 2],
       [3, 3, 4, 4]])

In [16]:
np.repeat(b,2, axis=0)

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4]])

In [17]:
np.repeat(b,2, axis=-1)

array([[1, 1, 2, 2],
       [3, 3, 4, 4]])

In [18]:
data

array([[1],
       [2],
       [3]])

In [19]:
np.roll(data, 1)

array([[3],
       [1],
       [2]])

In [20]:
np.roll(data, -1)

array([[2],
       [3],
       [1]])

In [21]:
np.roll(data, 2)

array([[2],
       [3],
       [1]])

In [22]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [23]:
np.diag(data, k=0)

array([1])

In [24]:
np.diag(data, k=1)

array([], dtype=int32)

In [25]:
a = np.array([[[1,2],[3,4],[5,6]]])

In [26]:
a

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [27]:
np.roll(a,1, axis = 1)

array([[[5, 6],
        [1, 2],
        [3, 4]]])

In [28]:
np.roll(a,1, axis = 0)

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [29]:
np.roll(a,1)

array([[[6, 1],
        [2, 3],
        [4, 5]]])

##### Binary Operations

In [30]:
arr1 = np.random.randint(1, 10, (3,4))

In [31]:
arr1

array([[3, 3, 2, 4],
       [7, 8, 8, 9],
       [3, 2, 9, 5]])

In [32]:
arr2 = np.random.randint(1, 10, (3,4))

In [33]:
arr2

array([[5, 7, 7, 9],
       [7, 9, 1, 7],
       [7, 1, 5, 2]])

In [34]:
arr1 + arr2

array([[ 8, 10,  9, 13],
       [14, 17,  9, 16],
       [10,  3, 14,  7]])

In [35]:
arr1 * arr2

array([[15, 21, 14, 36],
       [49, 72,  8, 63],
       [21,  2, 45, 10]])

In [36]:
arr1 / arr2

array([[0.6       , 0.42857143, 0.28571429, 0.44444444],
       [1.        , 0.88888889, 8.        , 1.28571429],
       [0.42857143, 2.        , 1.8       , 2.5       ]])

In [37]:
arr1 - arr2

array([[-2, -4, -5, -5],
       [ 0, -1,  7,  2],
       [-4,  1,  4,  3]])

In [38]:
arr1 ** arr2

array([[      243,      2187,       128,    262144],
       [   823543, 134217728,         8,   4782969],
       [     2187,         2,     59049,        25]])

In [39]:
arr1 > arr2

array([[False, False, False, False],
       [False, False,  True,  True],
       [False,  True,  True,  True]])

In [40]:
~arr1

array([[ -4,  -4,  -3,  -5],
       [ -8,  -9,  -9, -10],
       [ -4,  -3, -10,  -6]])

##### Numpy String Array

In [41]:
arr = np.array(["pw", "skills"])

In [42]:
arr

array(['pw', 'skills'], dtype='<U6')

In [43]:
np.char.upper(arr)

array(['PW', 'SKILLS'], dtype='<U6')

In [44]:
np.char.title(arr)

array(['Pw', 'Skills'], dtype='<U6')

In [45]:
arr1 = np.array(["saar", "hi"])

In [46]:
arr1

array(['saar', 'hi'], dtype='<U4')

In [47]:
np.char.capitalize(arr1)

array(['Saar', 'Hi'], dtype='<U4')

#####  Mathematical Functions

In [48]:
arr1 = np.random.randint(1, 10, (3,4))

In [49]:
arr1

array([[6, 3, 5, 6],
       [8, 2, 6, 4],
       [2, 3, 7, 9]])

In [50]:
np.sin(arr1)

array([[-0.2794155 ,  0.14112001, -0.95892427, -0.2794155 ],
       [ 0.98935825,  0.90929743, -0.2794155 , -0.7568025 ],
       [ 0.90929743,  0.14112001,  0.6569866 ,  0.41211849]])

In [51]:
np.cos(arr1)

array([[ 0.96017029, -0.9899925 ,  0.28366219,  0.96017029],
       [-0.14550003, -0.41614684,  0.96017029, -0.65364362],
       [-0.41614684, -0.9899925 ,  0.75390225, -0.91113026]])

In [52]:
np.tan(arr1)

array([[-0.29100619, -0.14254654, -3.38051501, -0.29100619],
       [-6.79971146, -2.18503986, -0.29100619,  1.15782128],
       [-2.18503986, -0.14254654,  0.87144798, -0.45231566]])

In [53]:
np.log10(arr1)

array([[0.77815125, 0.47712125, 0.69897   , 0.77815125],
       [0.90308999, 0.30103   , 0.77815125, 0.60205999],
       [0.30103   , 0.47712125, 0.84509804, 0.95424251]])

In [54]:
np.exp(arr1)

array([[4.03428793e+02, 2.00855369e+01, 1.48413159e+02, 4.03428793e+02],
       [2.98095799e+03, 7.38905610e+00, 4.03428793e+02, 5.45981500e+01],
       [7.38905610e+00, 2.00855369e+01, 1.09663316e+03, 8.10308393e+03]])

In [55]:
np.power(arr1, 2)

array([[36,  9, 25, 36],
       [64,  4, 36, 16],
       [ 4,  9, 49, 81]], dtype=int32)

In [56]:
np.mean(arr1)

5.083333333333333

In [57]:
np.max(arr1)

9

In [58]:
np.std(arr1)

2.2157893000513886

In [59]:
np.var(arr1)

4.909722222222222

In [60]:
np.min(arr1)

2

In [61]:
arr1 - arr2

array([[ 1, -4, -2, -3],
       [ 1, -7,  5, -3],
       [-5,  2,  2,  7]])

In [62]:
np.subtract(arr1, arr2)

array([[ 1, -4, -2, -3],
       [ 1, -7,  5, -3],
       [-5,  2,  2,  7]])

In [63]:
arr1 * arr2

array([[30, 21, 35, 54],
       [56, 18,  6, 28],
       [14,  3, 35, 18]])

In [64]:
np.multiply(arr1, arr2)

array([[30, 21, 35, 54],
       [56, 18,  6, 28],
       [14,  3, 35, 18]])

In [65]:
np.mod(arr1, arr2)

array([[1, 3, 5, 6],
       [1, 2, 0, 4],
       [2, 0, 2, 1]])

In [66]:
np.power(arr1, arr2)

array([[    7776,     2187,    78125, 10077696],
       [ 2097152,      512,        6,    16384],
       [     128,        3,    16807,       81]])

In [67]:
np.sqrt(arr1)

array([[2.44948974, 1.73205081, 2.23606798, 2.44948974],
       [2.82842712, 1.41421356, 2.44948974, 2.        ],
       [1.41421356, 1.73205081, 2.64575131, 3.        ]])

##### Sorting and Searching

In [69]:
arr = np.array([5,6,1,2])

In [70]:
arr

array([5, 6, 1, 2])

In [71]:
np.sort(arr)

array([1, 2, 5, 6])

In [73]:
arr = np.array([0,1,2,3,0,4])

In [74]:
np.sort(arr)

array([0, 0, 1, 2, 3, 4])

In [77]:
np.count_nonzero(arr)

4

In [78]:
arr > 0

array([False,  True,  True,  True, False,  True])

In [79]:
np.where(arr>0)

(array([1, 2, 3, 5], dtype=int64),)

In [81]:
np.where(arr == 0)

(array([0, 4], dtype=int64),)

In [82]:
np.extract(arr>0, arr)

array([1, 2, 3, 4])

In [83]:
arr

array([0, 1, 2, 3, 0, 4])

In [86]:
arr.byteswap()

array([       0, 16777216, 33554432, 50331648,        0, 67108864])

##### Matrix >> 2D array

In [88]:
import numpy.matlib as nm

In [90]:
nm.zeros(5, int)

matrix([[0, 0, 0, 0, 0]])

In [92]:
nm.ones((3,4),int)

matrix([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

##### Numpy Linear Algebra

In [96]:
arr1 = np.random.randint(1, 10, (3,4))
arr2 = np.random.randint(1, 10, (4,3))

In [97]:
arr1

array([[2, 2, 1, 4],
       [4, 1, 1, 5],
       [5, 2, 2, 6]])

In [98]:
arr2

array([[5, 4, 7],
       [3, 9, 8],
       [7, 3, 3],
       [6, 5, 2]])

In [100]:
arr1 @ arr2

array([[47, 49, 41],
       [60, 53, 49],
       [81, 74, 69]])

 ##### Linear Algebra

In [111]:
a = np.array([[7,5,-3],[2,-5,2],[5,6,-7]])

In [112]:
a

array([[ 7,  5, -3],
       [ 2, -5,  2],
       [ 5,  6, -7]])

In [113]:
b = np.array([16,-8,0])

In [114]:
b

array([16, -8,  0])

In [118]:
np.linalg.solve(a, b)

array([1.36470588, 3.85882353, 4.28235294])

In [119]:
a

array([[ 7,  5, -3],
       [ 2, -5,  2],
       [ 5,  6, -7]])

In [120]:
np.linalg.det(a)  # determinant

170.00000000000006

In [121]:
np.linalg.inv(a)  # inverse

array([[ 0.13529412,  0.1       , -0.02941176],
       [ 0.14117647, -0.2       , -0.11764706],
       [ 0.21764706, -0.1       , -0.26470588]])