In [3]:
import numpy as np

In [4]:
arr = np.ones((3,4), int)

In [5]:
arr

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [6]:
arr + 5

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

In [7]:
arr * 5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

#### np.empty()

In [8]:
np.empty((2,3), dtype = int)

array([[ 371501920,        506,          0],
       [         0,          1, 1818196321]])

In [9]:
np.empty((2,3), dtype = str)

array([['', '', ''],
       ['', '', '']], dtype='<U1')

In [10]:
np.empty((3,3), dtype = str)

array([['', '', ''],
       ['', '', ''],
       ['', '', '']], dtype='<U1')

#### np.eye()

In [11]:
np.eye(4, dtype = int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [12]:
# Optional Things

In [13]:
import pandas as pd

DataFrame: Multiple Rows and Multiple Columns

In [14]:
arr

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [15]:
pd.DataFrame(arr)

0  1  2  3
0  1  1  1  1
1  1  1  1  1
2  1  1  1  1

Explicit indexing is done by pandas

In [16]:
# Extra Topics

In [17]:
import random

Generating Random Data

In [18]:
random.choice((1,2,3,4,5,6))

5

In [19]:
random.choice("Saarthak")

'a'

In [20]:
random.randrange(1,1000)

864

In [21]:
random.random()  # Any random number between 0(included) and 1(excluded).

0.24266638433571086

In [22]:
l = [1,2,3,4,5,6]
random.shuffle(l)

In [23]:
l

[3, 5, 2, 4, 1, 6]

In [24]:
random.uniform(7,14) # A number between 7 and 14 with differnt distribution

7.547219380874755

#### Random np

In [25]:
np.random.rand(3,4)

array([[0.98675026, 0.43651275, 0.34652456, 0.60636407],
       [0.69114343, 0.53530317, 0.22627002, 0.19339131],
       [0.59866842, 0.37567118, 0.36137808, 0.49355754]])

In [26]:
np.random.rand(1)

array([0.67966788])

In [27]:
np.random.randn(2,3)

array([[ 1.21572404, -1.8469609 ,  1.58255144],
       [ 2.40429807,  0.35854247,  1.19156598]])

randn --> rand with Normal Distribution

In [28]:
np.random.random_sample()

0.3040526003167401

return random floats in the half-open interval [0.0, 1.0)
  (0 is included and 1 is excluded)

In [29]:
np.random.randint(1,5, size = (3,4))

array([[2, 4, 2, 4],
       [4, 1, 2, 1],
       [4, 4, 4, 4]])

randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).

In [30]:
arr = np.random.randint(1,5, size = (3,4))

In [31]:
arr

array([[1, 1, 1, 2],
       [4, 4, 2, 2],
       [4, 2, 2, 4]])

In [32]:
arr.size

12

In [33]:
arr.shape

(3, 4)

In [34]:
arr.ndim

2

#### Reshape Array

In [35]:
arr.reshape(2,6)

array([[1, 1, 1, 2, 4, 4],
       [2, 2, 4, 2, 2, 4]])

a.reshape(shape, order='C')

Returns an array containing the same data with a new shape.

array size cannot change

reshape(x,y) --> x*y = size of array

In [36]:
arr.reshape(12,2)

ValueError: cannot reshape array of size 12 into shape (12,2)

In [37]:
arr.reshape(12,1)

array([[1],
       [1],
       [1],
       [2],
       [4],
       [4],
       [2],
       [2],
       [4],
       [2],
       [2],
       [4]])

In [38]:
arr.reshape(4, -1)

array([[1, 1, 1],
       [2, 4, 4],
       [2, 2, 4],
       [2, 2, 4]])

-1 when we don't know how many columns we want

In [39]:
arr.reshape(3, -1)

array([[1, 1, 1, 2],
       [4, 4, 2, 2],
       [4, 2, 2, 4]])

In [40]:
arr.reshape(-1, 3)

array([[1, 1, 1],
       [2, 4, 4],
       [2, 2, 4],
       [2, 2, 4]])

In [41]:
arr.reshape(-1, 4)

array([[1, 1, 1, 2],
       [4, 4, 2, 2],
       [4, 2, 2, 4]])

In [42]:
arr.reshape(-1,5)

ValueError: cannot reshape array of size 12 into shape (5)

#### reshape().base  -->  Points out to original array

In [43]:
arr

array([[1, 1, 1, 2],
       [4, 4, 2, 2],
       [4, 2, 2, 4]])

In [44]:
arr.reshape(6,2)

array([[1, 1],
       [1, 2],
       [4, 4],
       [2, 2],
       [4, 2],
       [2, 4]])

In [45]:
arr.reshape(6,2).base

array([[1, 1, 1, 2],
       [4, 4, 2, 2],
       [4, 2, 2, 4]])

.base shows the array to which reshaping was done.

#### Reshape into another dimension

In [46]:
arr

array([[1, 1, 1, 2],
       [4, 4, 2, 2],
       [4, 2, 2, 4]])

In [47]:
arr.size

12

In [48]:
arr.ndim

2

In [49]:
arr2 = arr.reshape(2,3,2)

In [50]:
arr2

array([[[1, 1],
        [1, 2],
        [4, 4]],

       [[2, 2],
        [4, 2],
        [2, 4]]])

In [51]:
arr2.ndim

3

In [52]:
arr3 = arr.reshape(1,2,3,2)

In [53]:
arr3

array([[[[1, 1],
         [1, 2],
         [4, 4]],

        [[2, 2],
         [4, 2],
         [2, 4]]]])

In [54]:
arr3.ndim

4

#### Dimension Concepts

In [55]:
l = [1,2,3,4]

In [56]:
arr = np.array(l)

In [57]:
arr

array([1, 2, 3, 4])

In [58]:
arr.ndim

1

In [59]:
arr2 = np.array([[2,3],[4,5]])

In [60]:
arr2

array([[2, 3],
       [4, 5]])

In [61]:
arr2.ndim

2

In [62]:
arr2 = np.zeros((3,4))

In [63]:
arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [64]:
arr2.ndim

2

In [65]:
arr3 = np.zeros((1,3,4))  # 3 Rows & 4 Columns with 1 Extra Dimensions

In [66]:
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [67]:
arr3.ndim

3

In [68]:
arr3.shape

(1, 3, 4)

In [69]:
arr4 = np.zeros((1,2,2,3))

In [70]:
arr4

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [71]:
arr4.ndim

4

In [72]:
arr4.shape

(1, 2, 2, 3)

In [73]:
arr5 = np.zeros((2,3,4)) # 3by4 Matrix repeated twice in the extra dimension

In [74]:
arr5

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [75]:
arr5.ndim

3

In [76]:
arr5.shape

(2, 3, 4)

#### Operations on np-array

In [77]:
arr1 = np.random.randint(1,10,(5,6))

In [78]:
arr1

array([[3, 8, 8, 9, 5, 2],
       [5, 1, 1, 4, 8, 5],
       [3, 6, 4, 9, 3, 8],
       [8, 4, 7, 6, 4, 1],
       [1, 9, 4, 6, 7, 5]])

In [79]:
arr1>5

array([[False,  True,  True,  True, False, False],
       [False, False, False, False,  True, False],
       [False,  True, False,  True, False,  True],
       [ True, False,  True,  True, False, False],
       [False,  True, False,  True,  True, False]])

In [80]:
arr1[arr1>5]

array([8, 8, 9, 8, 6, 9, 8, 8, 7, 6, 9, 6, 7])

All the elements of arr1 where arr1>5 this condition is true

In [81]:
arr1[arr1 == 5]

array([5, 5, 5, 5])

#### Accessing elements and matrixs from array

In [82]:
arr

array([1, 2, 3, 4])

In [83]:
arr[0]

1

In [84]:
arr1

array([[3, 8, 8, 9, 5, 2],
       [5, 1, 1, 4, 8, 5],
       [3, 6, 4, 9, 3, 8],
       [8, 4, 7, 6, 4, 1],
       [1, 9, 4, 6, 7, 5]])

In [85]:
arr1[0,0]

3

In [86]:
arr1[0,1:4]

array([8, 8, 9])

In [87]:
arr1[0,[1,4]]

array([8, 5])

In [88]:
arr1[1:4, 2:5]

array([[1, 4, 8],
       [4, 9, 3],
       [7, 6, 4]])

In [89]:
arr1[[2,4],[2,4]]

array([4, 7])

In [90]:
arr1[2:,2:4]

array([[4, 9],
       [7, 6],
       [4, 6]])

In [91]:
arr1[[0,4], ]

array([[3, 8, 8, 9, 5, 2],
       [1, 9, 4, 6, 7, 5]])

In [92]:
arr1[[0,4], 0:3]

array([[3, 8, 8],
       [1, 9, 4]])

#### Operations on 2 arrays

In [93]:
arr1 = np.random.randint(1,3,(3,3))

In [94]:
arr1

array([[1, 1, 2],
       [1, 1, 2],
       [2, 2, 2]])

In [95]:
arr2 = np.random.randint(1,3,(3,3))

In [96]:
arr2

array([[1, 2, 1],
       [1, 2, 2],
       [1, 2, 1]])

In [97]:
arr1 + arr2

array([[2, 3, 3],
       [2, 3, 4],
       [3, 4, 3]])

In [98]:
arr1 * arr2

array([[1, 2, 2],
       [1, 2, 4],
       [2, 4, 2]])

In [99]:
arr1 - arr2

array([[ 0, -1,  1],
       [ 0, -1,  0],
       [ 1,  0,  1]])

In [107]:
arr1 / arr2  # Indexwise division

array([[1. , 0.5, 2. ],
       [1. , 0.5, 1. ],
       [2. , 1. , 2. ]])

In [100]:
arr1 // arr2

array([[1, 0, 2],
       [1, 0, 1],
       [2, 1, 2]])

In [101]:
arr1 % arr2

array([[0, 1, 0],
       [0, 1, 0],
       [0, 0, 0]])

#### Matrix Multiplication 

In [102]:
arr1

array([[1, 1, 2],
       [1, 1, 2],
       [2, 2, 2]])

In [103]:
arr2

array([[1, 2, 1],
       [1, 2, 2],
       [1, 2, 1]])

In [104]:
arr1 @ arr2

array([[ 4,  8,  5],
       [ 4,  8,  5],
       [ 6, 12,  8]])

In [108]:
5/0

ZeroDivisionError: division by zero

In [109]:
arr1/0

C:\Users\saart\AppData\Local\Temp\ipykernel_12752\1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

###### Numpy Understands Infinity where is Python is not capable of doing that

### Broad Casting

In [113]:
arr = np.zeros((3,4), int)

In [114]:
arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [115]:
arr + 5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

 ###### 5 is added to all elements, This is Broadcasting.

In [139]:
a = np.array([1,2,3,4])

In [140]:
a

array([1, 2, 3, 4])

In [141]:
arr + a

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [142]:
b = np.array([1,2,3,4,5])

In [143]:
b

array([1, 2, 3, 4, 5])

In [144]:
arr + b

ValueError: operands could not be broadcast together with shapes (3,4) (5,) 

#### Transpose an array --->  Rows to Columns and Columns to Rows 

In [168]:
d = np.asarray([[1,2,3]])

In [169]:
d

array([[1, 2, 3]])

In [170]:
d.shape

(1, 3)

In [175]:
dt = d.T  # array.T

In [178]:
dt

array([[1],
       [2],
       [3]])

In [176]:
dt.shape

(3, 1)

In [173]:
arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [177]:
arr + dt

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3]])

###### for Transpose array must be in 2 dimension

In [181]:
arr1

array([[1, 1, 2],
       [1, 1, 2],
       [2, 2, 2]])

In [182]:
np.sqrt(arr1)

array([[1.        , 1.        , 1.41421356],
       [1.        , 1.        , 1.41421356],
       [1.41421356, 1.41421356, 1.41421356]])

In [183]:
np.log10(arr1)

array([[0.     , 0.     , 0.30103],
       [0.     , 0.     , 0.30103],
       [0.30103, 0.30103, 0.30103]])

In [184]:
np.exp(arr1)

array([[2.71828183, 2.71828183, 7.3890561 ],
       [2.71828183, 2.71828183, 7.3890561 ],
       [7.3890561 , 7.3890561 , 7.3890561 ]])

In [185]:
np.mean(arr1)

1.5555555555555556

In [186]:
a

array([1, 2, 3, 4])

In [187]:
np.min(a)

1

In [188]:
np.min(arr1)

1

In [189]:
np.max(arr1)

2

In [190]:
arr1

array([[1, 1, 2],
       [1, 1, 2],
       [2, 2, 2]])

In [191]:
arr1.T

array([[1, 1, 2],
       [1, 1, 2],
       [2, 2, 2]])

#### Reduce Higher Dimension to One Dimension

In [195]:
arr1

array([[1, 1, 2],
       [1, 1, 2],
       [2, 2, 2]])

In [199]:
a_f = arr1.flatten()

In [200]:
a_f

array([1, 1, 2, 1, 1, 2, 2, 2, 2])

In [214]:
arr = np.array([[1,2,3], [4,5,6]])

In [215]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [216]:
np.sum(arr)

21

##### Axis 0  >>  Rows

In [217]:
np.sum(arr, axis=0)

array([5, 7, 9])

##### Axis 1 >> Columns

In [218]:
np.sum(arr, axis=1)

array([ 6, 15])

###  expand_dims  >>  expands the array by inserting new axis

In [224]:
arr = np.array([1,2,3,4])

In [225]:
arr

array([1, 2, 3, 4])

In [226]:
arr.ndim

1

In [228]:
arr1 = np.expand_dims(arr, axis = 0)

In [229]:
arr1

array([[1, 2, 3, 4]])

In [230]:
arr1.ndim

2

In [231]:
arr2 = np.expand_dims(arr1, axis = 0)

In [232]:
arr2

array([[[1, 2, 3, 4]]])

In [233]:
arr2.ndim

3

In [240]:
arr1 = np.expand_dims(arr, axis = 1)

In [241]:
arr1

array([[1],
       [2],
       [3],
       [4]])

In [242]:
arr1.ndim

2

In [243]:
arr = np.zeros((3,4))

In [244]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [247]:
arr.ndim

2

In [245]:
arr1 = np.expand_dims(arr, axis = 1)

In [246]:
arr1

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [248]:
arr1.ndim

3

In [234]:
arr

array([1, 2, 3, 4])

In [249]:
arr.ndim

2

In [237]:
arr.reshape(2,-1)

array([[1, 2],
       [3, 4]])

In [239]:
arr.reshape(2,-1).ndim

2